"""empty message

Revision ID: 20dcb27c121e
Revises: d62230d7051d
Create Date: 2022-10-25 16:13:19.259230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20dcb27c121e'
down_revision = 'd62230d7051d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('pokemon', sa.Column('base_exp', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('ability', sa.String(), nullable=True))
    op.add_column('pokemon', sa.Column('base_hp', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('base_att', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('base_def', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'base_def')
    op.drop_column('pokemon', 'base_att')
    op.drop_column('pokemon', 'base_hp')
    op.drop_column('pokemon', 'ability')
    op.drop_column('pokemon', 'base_exp')
    op.drop_column('pokemon', 'name')
    # ### end Alembic commands ###
